# 실행 방식 "raw_count"(한 도메인에 대하여 출현한 절대 개수) or "presence_count"(한 도메인에 대하여 출현한 문서 개수/전체 문서 개수 비율)
mode: "presence_count" 

# domain, term 테이블 초기화가 필요한 경우 true, 아닌경우(추가로 여러 도메인이 들어우는 경우) false / Default: false
db_truncate: false

annotation_edit:
  thresholds:     
    - threshold: 1000
      suffix: "_2"    
  default_suffix: "_1"